---
name: Build&Release DocSpace plugins

on: 
  push:
    paths-ignore:
      - '.github/**'
      
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.plugins }}
    steps:
    - uses: actions/checkout@v4
    - name: make matrix
      id: matrix
      run: |
        PLUGINS=()
        for d in $(ls -d */); do
          if [[ -f ${d}/yarn.lock || -f ${d}/package.json ]]; then
            PLUGINS+=($(basename ${d}))
          fi
        done
        echo "plugins for build is: "
        echo "${PLUGINS[@]}"

        # Set new matrix for build job
        echo "plugins=$(jq -c -n '$ARGS.positional' --args "${PLUGINS[@]}")" >> "$GITHUB_OUTPUT"
          
  build:
    name: "Build plugin: ${{ matrix.plugin }}"
    runs-on: ubuntu-latest
    env:
      PLUGIN_FOLDER: ${{ matrix.plugin }}
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix: 
        plugin: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
    
    # Get s3 plugins name
    - name: Get s3 plugin name
      run: |
        echo "PLUGIN_NAME=$(cat ./${PLUGIN_FOLDER}/package.json | jq -r '.name' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
        
    - name: Build plugin
      run: |
        cd ./${PLUGIN_FOLDER}
        yarn
        yarn run build

    - name: Configure AWS Credentials
      if: github.ref_name == 'master'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: extract plugins.zip
      if: github.ref_name == 'master'
      run: |
        mkdir -p ../${PLUGIN_NAME}
        unzip ./${PLUGIN_FOLDER}/dist/plugin.zip -d ../${PLUGIN_NAME}

    - name: Upload plugin
      if: github.ref_name == 'master'
      run: |
        cd ../
        aws s3 sync ./${PLUGIN_NAME} s3://docspace-static.onlyoffice.io/webplugins/${PLUGIN_NAME}
